# src/brahma/domain/entities/paper.py
"""Domain entities for papers, sections, and chunks.

These are immutable dataclasses that model the core business objects used by the
application layer.  They live in the *domain* package to stay free of any
framework or infrastructure concerns.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional
from uuid import UUID, uuid4


class DomainError(RuntimeError):
    """Base class for domain‑specific exceptions."""


class EmptySectionError(DomainError):
    """Raised when a :class:`Section` contains only whitespace after stripping."""


@dataclass(frozen=True, slots=True)
class Section:
    """A logical section of a paper (e.g. Introduction, Methods)."""

    heading: str
    content: str

    def is_empty(self) -> bool:
        """Return ``True`` if the section has no non‑whitespace content."""
        return not self.content.strip()


@dataclass(frozen=True, slots=True)
class Paper:
    """Aggregate root representing an entire scholarly paper."""

    paper_id: UUID
    title: str
    doi: Optional[str] = None
    pmid: Optional[str] = None
    sections: List[Section] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class Chunk:
    """A token‑aware slice of a paper section.

    ``chunk_id`` is generated by the ``Chunker`` service; ``paper_id`` links
    back to the parent :class:`Paper`.
    """

    chunk_id: UUID
    paper_id: UUID
    section_name: str
    chunk_text: str
